<?php
// lang-en.php — testi dell'interfaccia in inglese.
//
// Stesse chiavi di lang-it.php. Una chiave che manca qui compare in italiano:
// meglio tradurre tutto, ma una dimenticanza non lascia buchi.
//
// Terminologia, allineata a terms-en.html e privacy-en.html:
// scheda = workout, allenamento (la sessione) = session, cestino = bin.

return [
    // --- Lingua ---------------------------------------------------------------
    "lang.name"   => "English",
    "lang.locale" => "en_US",

    // --- Documenti legali -----------------------------------------------------
    "doc.terms"       => "Terms of use",
    "doc.terms_url"   => "terms-en.html",
    "doc.privacy"     => "Privacy policy",
    "doc.privacy_url" => "privacy-en.html",

    // --- Comuni ---------------------------------------------------------------
    "common.error"           => "Error.",
    "common.network_error"   => "Network error. Try again.",
    "common.need_network"    => "You need a connection.",
    "common.need_name"       => "A name is required.",
    "common.loading"         => "Loading…",
    "common.home"            => "← Home",
    "common.copied"          => "✓ Copied",
    "common.name"            => "Name",
    "common.sets"            => "Sets",
    "common.reps"            => "Reps",
    "common.link_optional"   => "Link (optional)",
    "common.back_to_workout" => "Back to the session",
    "common.view_exercise"   => "View exercise ↗",
    "common.first_word"      => "First word",
    "common.second_word"     => "Second word",
    "common.account"         => "Account",
    "common.manage_workouts" => "Manage workouts",
    "common.workout"         => "Workout",
    "common.cancel"          => "Cancel",
    "common.save"            => "Save",

    // --- Accesso e registrazione ----------------------------------------------
    "login.username"    => "Username",
    "login.submit"      => "Sign in",
    "login.to_register" => "No account yet? Sign up",
    "login.failed"      => "Sign-in failed",
    "reg.hint"          => "Two words you can easily remember, at least 3 letters each. You will need them to sign in, together with your username.",
    "reg.accept"        => "By creating an account you accept the {terms} and the {privacy}. The service is provided as is: no warranty, no backups, no support.",
    "reg.submit"        => "Create account",
    "reg.to_login"      => "Already have an account? Sign in",
    "reg.failed"        => "Sign-up failed",
    "app.logout"        => "Sign out",

    // --- Coda offline e annulla serie -----------------------------------------
    "queue.count.one"   => "{n} set queued",
    "queue.count.other" => "{n} sets queued",
    "queue.rejected"    => "A set was rejected by the server.",
    "undo.none"         => "No set to undo.",
    "undo.confirm"      => "Undo the last recorded set?",
    "undo.done"         => "Set undone",

    // --- Home -----------------------------------------------------------------
    "home.title"              => "Your workouts",
    "home.never"              => "never done",
    "home.today"              => "today",
    "home.yesterday"          => "yesterday",
    "home.days_ago.one"       => "{n} day ago",
    "home.days_ago.other"     => "{n} days ago",
    "home.empty_edit"         => "No workouts. Create one below.",
    "home.empty"              => "No workouts. Go to «Manage workouts» to create one.",
    "home.new_workout"        => "+ New workout",
    "home.import"             => "Import from a link",
    "home.done"               => "Done",
    "home.history"            => "Training history",
    "home.hide_deleted"       => "Hide deleted",
    "home.show_deleted"       => "Show deleted ({n})",
    "home.trash_note"         => "Deleted workouts are gone for good after 30 days.",
    "home.new_name_prompt"    => "Name of the new workout:",
    "home.created"            => "Workout created",
    "home.trash_confirm"      => "Move «{name}» to the bin?\nIt will be gone for good after 30 days. Your history stays.",
    "home.trashed"            => "Moved to the bin",
    "home.restored"           => "Restored",
    "home.need_network_start" => "You need a connection to start a session.",
    "home.open_failed"        => "Could not open the workout.",

    // --- Player ---------------------------------------------------------------
    "player.progress"     => "Exercise {n} of {total}",
    "player.target"       => "Target {target}",
    "player.set"          => "Set {n} of {total}",
    "player.weight"       => "Weight (kg)",
    "player.seconds"      => "Seconds",
    "player.next"         => "Next",
    "player.add_set"      => "+ Set",
    "player.skip"         => "Skip exercise",
    "player.alternative"  => "Alternative",
    "player.undo"         => "↶ Undo set",
    "player.rest"         => "Rest",
    "player.rest_skip"    => "skip",
    "player.finish"       => "Finish session",
    "player.cancel"       => "Discard session",
    "player.exlist_title" => "Exercises in this workout",
    "player.exlist_hint"  => "Tap an exercise to do it now.",
    "player.set_logged"   => "✓ Set recorded",
    "player.set_added"    => "Set added",
    "player.skipped"      => "✓ Skipped",
    "player.last_time"    => "Last time: {sets}",
    "player.rest_over"    => "Rest over",
    "player.stopped_at"   => "Stopped at {s}s",
    "player.set_seconds"  => "Set the seconds in the workout.",
    "player.time_up"      => "Time!",
    "player.work_stop"    => "■ Stop — {s}s",
    "player.work_start_s" => "▶ Start {s}s",
    "player.work_start"   => "▶ Start",

    // --- Alternative ----------------------------------------------------------
    "alt.need_network"     => "You need a connection to manage alternatives.",
    "alt.instead_of"       => "Instead of {name}",
    "alt.used"             => "Already used",
    "alt.new"              => "New alternative",
    "alt.use"              => "Use this alternative",
    "alt.need_network_add" => "You need a connection to add an alternative.",
    "alt.replaced_with"    => "Replaced with {name}",

    // --- Fine allenamento -----------------------------------------------------
    "finish.title"            => "Session complete",
    "finish.substitutions"    => "Substitutions",
    "finish.make_permanent"   => "Make «{name}» permanent instead of «{primary}»",
    "finish.note"             => "Note (optional)",
    "finish.note_placeholder" => "How it went, aches, energy…",
    "finish.save"             => "Save and close",
    "finish.sub_not_saved"    => "Substitution not saved (offline).",
    "finish.offline"          => "You're offline: the session will be closed when you reconnect.",
    "finish.cancel_confirm"   => "Discard this session? Nothing will be saved.",
    "finish.cancelled"        => "Session discarded.",
    "finish.saved"            => "Session saved",
    "finish.copy"             => "📋 Copy summary",
    "finish.copy_failed"      => "Copy failed: the text is selected, copy it by hand.",
    "finish.home"             => "Back to home",
    "summary.note"            => "Note: {text}",

    // --- Editor della scheda --------------------------------------------------
    "edit.need_network" => "You need a connection to edit the workout.",
    "edit.title"        => "Edit workout",
    "edit.name"         => "Workout name",
    "edit.save_name"    => "Save name",
    "edit.exercises"    => "Exercises",
    "edit.add_exercise" => "+ Add exercise",
    "edit.hide_deleted" => "Hide deleted",
    "edit.show_deleted" => "Show deleted ({n})",
    "edit.trash_note"   => "Deleted exercises are gone for good after 30 days.",
    "edit.meta_rest"    => "rest {s}s",
    "edit.meta_link"    => "link",
    "edit.meta_alt"     => "{n} alt",

    // --- Esercizio ------------------------------------------------------------
    "ex.edit_title"         => "Edit exercise",
    "ex.new_title"          => "New exercise",
    "ex.type"               => "Type",
    "ex.type_reps"          => "By reps",
    "ex.type_time"          => "Timed (seconds)",
    "ex.rest"               => "Rest (seconds)",
    "ex.hold_seconds"       => "Hold (seconds)",
    "ex.saved"              => "Saved",
    "ex.alternatives_title" => "Alternatives for this exercise",
    "ex.alternatives_note"  => "These are the substitutions already used instead of this exercise. Removing one stops it from being suggested.",
    "ex.name_empty"         => "The name cannot be empty.",
    "ex.name_updated"       => "Name updated",
    "ex.trash_confirm"      => "Delete «{name}»?\nIt stays in the bin for 30 days. Your history is not touched.",
    "ex.trashed"            => "Moved to the bin",
    "ex.alt_remove_confirm" => "Remove «{name}» from the alternatives?",
    "ex.alt_removed"        => "Alternative removed",
    "ex.restored"           => "Restored",

    // --- Condivisione e import ------------------------------------------------
    "share.title"          => "Sharing",
    "share.off_note"       => "Not shared. Turn it on to get a link you can send to anyone: whoever has it can see the workout and import it.",
    "share.enable"         => "Turn on sharing",
    "share.copy_link"      => "📋 Copy link",
    "share.copy_failed"    => "Copy failed.",
    "share.revoke"         => "Revoke sharing",
    "share.revoke_confirm" => "Revoke sharing?\nThe link will stop working. Anyone who already imported it keeps their copy.",
    "share.enabled"        => "Sharing on",
    "share.revoked"        => "Sharing revoked",
    "import.prompt"        => "Paste the link or code of the shared workout:",
    "import.need_code"     => "A code is required.",
    "import.done"          => "Workout imported",
    "import.confirm"       => "Import the shared workout into your account?",

    // --- Account --------------------------------------------------------------
    "account.signed_in_as"   => "Signed in as {name}",
    "account.warning"        => "We don't ask for an email or any other personal data. That's why your credentials CANNOT be recovered: if you forget your username or your two words, nobody can reach the account or its data anymore. Write them down somewhere safe.",
    "account.delete_title"   => "Delete account",
    "account.delete_text"    => "Permanently deletes the account and everything in it: workouts, exercises and training history. It cannot be recovered. Workouts that others have imported stay theirs.",
    "account.delete_button"  => "Delete permanently",
    "account.need_words"     => "Enter your two words to confirm.",
    "account.delete_confirm" => "Permanently delete your account?\n\nWorkouts, exercises and your whole history will be gone. This cannot be undone or recovered.",

    // --- Storico --------------------------------------------------------------
    "history.title"        => "History",
    "history.need_network" => "You need a connection to see your history.",
    "history.load_failed"  => "Could not load your history.",
    "history.empty"        => "No sessions recorded yet.",

    // --- Pagina pubblica ------------------------------------------------------
    "public.not_found_title" => "Workout not available — Ghisa",
    "public.not_found_desc"  => "This workout does not exist, or sharing has been revoked.",
    "public.not_found_text"  => "This workout does not exist, or sharing was revoked by whoever published it.",
    "public.title"           => "{name} — workout | Ghisa",
    "public.desc.one"        => "{n} exercise: {list}",
    "public.desc.other"      => "{n} exercises: {list}",
    "public.go"              => "Go to Ghisa",
    "public.kicker"          => "Shared workout",
    "public.empty"           => "This workout has no exercises yet.",
    "public.rest"            => "rest {s}s",
    "public.import"          => "Import this workout into Ghisa",
    "public.foot"            => "{brand} is an app to follow your workouts from your phone and keep a history of your loads.",

    // --- Errori dal server ----------------------------------------------------
    "err.session_expired"          => "Session expired",
    "err.username_length"          => "The username must be between 3 and 50 characters",
    "err.username_chars"           => "The username can only contain letters, numbers, dot, hyphen and underscore",
    "err.words_length"             => "Each of the two words must be at least 3 characters long",
    "err.username_taken"           => "Username already taken",
    "err.registration_closed"      => "Sign-up for new accounts is closed.",
    "err.too_many_attempts"        => "Too many attempts. Try again in a few minutes.",
    "err.invalid_credentials"      => "Invalid credentials",
    "err.words_mismatch"           => "The two words don't match",
    "err.workout_not_found"        => "Workout not found",
    "err.session_not_found"        => "Session not found",
    "err.exercise_not_found"       => "Exercise not found",
    "err.primary_not_found"        => "Main exercise not found",
    "err.alternative_not_found"    => "Alternative not found",
    "err.alternative_name_missing" => "Alternative name missing",
    "err.client_uid_invalid"       => "Missing or invalid client_uid",
    "err.client_uid_missing"       => "Missing client_uid",
    "err.set_number_invalid"       => "Invalid set_number",
    "err.url_invalid"              => "Invalid URL (use http:// or https://)",
    "err.name_empty"               => "The name cannot be empty",
    "err.type_invalid"             => "Invalid type",
    "err.nothing_to_reorder"       => "Nothing to reorder",
    "err.share_code_invalid"       => "Invalid code, or sharing has been revoked",
    "err.unknown_action"           => "Unknown action",
    "err.internal"                 => "Internal error",
];
